version: "3.2"

services:
  mysql:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Sonv29$lR&Ks
      MYSQL_HOST: '%'
  
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass Tlqm520